version: "3.9"

services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=adminpostgre
      - POSTGRES_PASSWORD=87654321
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/posgresql/data

  pg-admin:
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=dzakitajudin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"

volumes:
  data: